num_threads: 4
num_hidden_layers: 2
neurons_per_hidden: [4, 3]
learning_rate: 0.1
activation_functions: ["relu", "tanh", "linear"]
num_epochs: 10
dataset_files: ["./dataset/data1.csv", "./dataset/data2.csv", "./dataset/data3.csv", "./dataset/data4.csv"]
# Optional metrics to evaluate after training
metrics: ["Accuracy","Loss", "MAE", "RMSE", "R2", "Confusion Matrix", "AUC"] #"Accuracy",
